Option for the dependent jobs added
os-autoinst/scripts pull request #124
Opened 2021-12-20 12:07 UTC by jankohoutek

Now there is an option to run the jobs also with their dependencies.
Needed if the outtake of requests needs to be done in jobs before the failed ones.

2021-12-20 12:24 UTC, okurz requested changes
please phrase the git commit message according to https://github.com/os-autoinst/scripts#rules-for-commits , i.e. with imperative mood

2021-12-20 12:24 UTC, okurz commented on openqa-trigger-bisect-jobs
> +      default_opts = ['--within-instance','--parental-inheritance']
```suggestion
    if include_depends:
      default_opts = ['--within-instance','--parental-inheritance']
```

2021-12-20 12:24 UTC, okurz commented on openqa-trigger-bisect-jobs
> +                        help='Restart also the jobs on which investigated one is dependant')
```suggestion
    parser.add_argument('--include-depends', action='store_true', default=False,
                        help='Restart also the jobs on which the investigated one depends')
```

2022-01-17 14:13 UTC, okurz reviewed
The option certainly does what you want but the idea for "openqa-trigger-bisect-jobs" was that it does what is needed to do to bisect any regression. And how should the caller decide if they need the option "--include-depends" or not? The problem that motivated you was a package change that affected the parent installation job already, right? I am wondering, if we would simply always do that, what would be the drawbacks?

2022-04-26 12:32 UTC, kalikiana commented
> The option certainly does what you want but the idea for "openqa-trigger-bisect-jobs" was that it does what is needed to do to bisect any regression. And how should the caller decide if they need the option "--include-depends" or not? The problem that motivated you was a package change that affected the parent installation job already, right? I am wondering, if we would simply always do that, what would be the drawbacks?

This doesn't seem to be linked to a ticket or issue but [#95783](https://progress.opensuse.org/issues/95783#note-41) touches on very similar points.

2022-09-29 13:48 UTC, okurz commented
closing due to no response. At any point feel free to address the open points and re-open.

2022-09-29 14:16 UTC, closed without merging