Bisect only failed jobs
os-autoinst/scripts pull request #144
Opened 2022-04-11 13:39 UTC by perlpunk

I somehow thoght the hook was only called for failed jobs.

But I saw this in our logs:
    Traceback (most recent call last):
      File "/opt/os-autoinst-scripts/openqa-trigger-bisect-jobs", line 120, in <module>
        main(parse_args())
      File "/opt/os-autoinst-scripts/openqa-trigger-bisect-jobs", line 79, in main
        for line in investigation['diff_to_last_good'].split('\n'):
    KeyError: 'diff_to_last_good'

Issue: https://progress.opensuse.org/issues/107014

2022-04-11 13:40 UTC, okurz requested changes
The change is ok but this is not about "failed" or "passed" but rather that there can be jobs which do not have investigation info or jobs that never had a last good but always failed.

2022-04-11 13:41 UTC, Martchus approved these changes

2022-04-11 13:53 UTC, perlpunk commented
I looked into the gru journal, looked at the error timestamp, then looked into the openqa_gru log fo the timestamp, found a minion id, for example https://openqa.suse.de/minion/jobs?id=4258325
And then I looked into the job https://openqa.suse.de/tests/8506934

2022-04-12 16:22 UTC, mimi1vx approved these changes

2022-04-13 09:01 UTC, okurz approved these changes

2022-04-13 09:01 UTC, merged