Set _TRIGGER_JOB_DONE_HOOK=1 for investigation jobs
os-autoinst/scripts pull request #193
Opened 2022-12-21 16:47 UTC by perlpunk

Issue: https://progress.opensuse.org/issues/98862

Should only be merged after #192

2022-12-22 12:16 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

2023-01-25 13:07 UTC, Martchus requested changes

2023-01-25 13:07 UTC, Martchus commented on openqa-investigate
> +    clone_settings=("TEST+=:investigate$name_suffix" ''_TRIGGER_JOB_DONE_HOOK=1' _GROUP_ID=0' 'BUILD=')
The quoting looks a little odd.

2023-01-25 13:41 UTC, perlpunk commented on openqa-investigate
> +    clone_settings=("TEST+=:investigate$name_suffix" ''_TRIGGER_JOB_DONE_HOOK=1' _GROUP_ID=0' 'BUILD=')
Oops. fixed

2023-01-25 13:49 UTC, perlpunk commented on openqa-investigate
> +    clone_settings=("TEST+=:investigate$name_suffix" ''_TRIGGER_JOB_DONE_HOOK=1' _GROUP_ID=0' 'BUILD=')
and pushed...

2023-01-25 13:54 UTC, Martchus approved these changes

2023-01-25 14:06 UTC, kalikiana approved these changes

2023-01-25 22:33 UTC, okurz approved these changes

2023-01-25 22:33 UTC, merged