Add openqa-get-job-incidents
os-autoinst/scripts pull request #212
Opened 2023-02-13 10:22 UTC by grisu48

Adds file for querying the incidents of openQA test runs (OSD only).

2023-02-13 13:54 UTC, Martchus commented on openqa-get-job-incidents
> +
```suggestion
```

2023-02-13 15:39 UTC, grisu48 commented on openqa-get-job-incidents
> +
Done.

2023-02-14 13:44 UTC, okurz requested changes
Please change the file to use 4 tabs for indention. See existing files like https://github.com/os-autoinst/scripts/blob/master/openqa-trigger-bisect-jobs. Also please add at least a minimal corresponding test module in https://github.com/os-autoinst/scripts/tree/master/tests

2023-02-15 10:55 UTC, okurz commented
please add at least a minimal corresponding test module in https://github.com/os-autoinst/scripts/tree/master/tests

2023-02-15 10:56 UTC, okurz requested changes
please add at least a minimal corresponding test module in https://github.com/os-autoinst/scripts/tree/master/tests

2023-02-28 12:50 UTC, grisu48 commented
No time right now to do additional work here. I might consider a resubmission later.

2023-02-28 12:50 UTC, closed without merging