Mention when force result will not be applied
os-autoinst/scripts pull request #263
Opened 2023-09-28 10:19 UTC by kalikiana

To distinguish from other cases where the result was not applied and avoid having to second-guess after the fact.

See: https://progress.opensuse.org/issues/135782

2023-09-28 11:46 UTC, perlpunk commented on openqa-label-known-issues
> +                    label="$label (Ignoring force result for ticket which is not in $force_result_tracker)"
Maybe add the word "tracker" explicitly because most people don't know

2023-09-28 11:57 UTC, Martchus commented on openqa-label-known-issues
> +                    label="$label (Ignoring force result for ticket which is not in $force_result_tracker)"
```suggestion
                    label="$label (ignoring force result for ticket which is not in tracker \"$force_result_tracker\")"
```

2023-09-28 13:35 UTC, okurz requested changes
Neat idea. Can you reference examples at best from o3 showing the new case?

2023-09-28 14:05 UTC, Martchus approved these changes

2023-10-02 13:40 UTC, kalikiana commented
> Neat idea. Can you reference examples at best from o3 showing the new case?

<img width="642" alt="Screenshot 2023-10-02 at 15 39 04" src="https://github.com/os-autoinst/scripts/assets/1204189/4a5d7fbe-7b48-46b3-b647-b7a193cbc69f">

See https://openqa.opensuse.org/tests/3583961#comments

2023-10-02 13:43 UTC, perlpunk approved these changes

2023-10-02 17:04 UTC, okurz approved these changes

2023-10-02 17:05 UTC, merged